country_name: "libya"
ssp_input_file_name: "LBY_real_data_20250718.csv"
ssp_transformation_cw: "ssp_libya_transformation_cw_ndc.xlsx"
set_lndu_reallocation_factor_to_zero: true
energy_model_flag: true